---
title: Speedy Wunderground
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  releases:
    title: Releases
    output: true
- scope:
    path: ''
    type: releases
  values:
    price: 119.99
    sku:
    image:
    file-guid:
    shippable:
    layout: productdetails

# Build settings
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
