---
title: Speedy Wunderground
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  releases:
    title: Releases
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: releases
  values:
    layout: productdetails
    categories: 
    price: 
    sku: 
    image: 
    file-guid: 
    shippable: 
    mp3-asset: 
    tracks:
    - name: 
      file: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
    thumbnail_image: 
    image: 
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/speedywunderground"
url: ''
twitter_username: speedywunder
github_username: maxray
facebook_username: fb.com/speedywunder/
api_key: OGIyYTBkODgtNzJkZS00MjI1LWEwOTUtNDcwOGZiNDA1OGVmNjM2OTQxMTA2MDUxMTYxMzQ3
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
